name: VenturaClassroom
version: '${project.version}'
main: net.bov.main.VenturaClassroom
api-version: '1.16'
author: Ash10744
description: A classroom system for your server.
softdepend: [Vault, PlaceholderAPI]

commands:
  class:
    description: Main command for VenturaClassroom
    usage: /<command>
    aliases: [classes, classroom, vclass, vclassroom]

permissions:
  venturaclasses.use:
    description: Join and view classes
    default: true
  venturaclasses.teacher:
    description: Run a class you are assigned to
    default: op
  venturaclasses.admin:
    description: Create and configure classes
    default: op